volumes:
  n8n_storage:

networks:
  nganunetwork:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ["nganunetwork"]
  environment:
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_RESTRICT_FILE_ACCESS_TO=/data/payslips
  env_file:
    - path: .env
      required: false

services:
  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        n8n import:workflow --separate --input=/workflows
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/workflows:/workflows

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: payslips
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/workflows:/workflows
      - ./payslips:/data/payslips
    depends_on:
      n8n-import:
        condition: service_completed_successfully
